name: Build_M1Store
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Theos and SDK
        run: |
          # دابەزاندنی تیۆس
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # دابەزاندنی ئێس دی کەی (ئەمە کێشەکەت چارەسەر دەکات)
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          make
          
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: M1Store_Files
          path: |
            .theos/obj/debug/*.dylib
            packages/*.deb
